### ISSUE TITLE
Req: Add SLN file to the git repo

### ISSUE THREAD

**Issue by HakanL** [advancedrei/sendgridplus-csharp#7]
Makes it easier :)

Also, why are there multiple folders for .NET4, 4.5, etc? The code looks very portable to not require duplicate files?

**Comment by robertmclaws** [comment]
There are multiple folders because .NET 4 and 4.5 support the SMTP transport, which the Portable library does not.

**Comment by robertmclaws** [comment]
Thanks for this, looks like I missed a few files in the first checkin. Should be fixed now.

**Comment by HakanL** [comment]
Thanks!

But couldn't .NET4 and 4.5 be the same, they both provide the SMTP transport?

**Comment by robertmclaws** [comment]
I like having separate builds because each runtime has separate optimizations, GC enhancements, etc. Since I forked this version primarily for me, I like having all my binaries compiled on the latest version wherever possible. The .NET 4.0 version is only provided for people that asked for it, and the code files are linked, not duplicated.

**Comment by HakanL** [comment]
I understand, that makes sense.
